#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
using namespace std;

string findLCS(const string &X, const string &Y) {
    int m = X.size(), n = Y.size();
    vector<vector<int>> dp(m + 1, vector<int>(n + 1, 0));

    for (int i = 1; i <= m; i++) {
        for (int j = 1; j <= n; j++) {
            if (X[i - 1] == Y[j - 1])
                dp[i][j] = dp[i - 1][j - 1] + 1;
            else
                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]);
        }
    }

    string lcs = "";
    int i = m, j = n;
    while (i > 0 && j > 0) {
        if (X[i - 1] == Y[j - 1]) {
            lcs = lcs + X[i - 1];
            i--;
            j--;
        } else if (dp[i - 1][j] > dp[i][j - 1]) {
            i--;
        } else {
            j--;
        }
    }
    reverse(lcs.begin(),lcs.end());
    return lcs;
}


string longestCommonSubsequence(const vector<string> &grades)
{
    if (grades.empty())
        return "";

    string lcs = grades[0];

    for (int i = 1; i < grades.size(); i++)
    {
        lcs = findLCS(lcs, grades[i]);
    }
    return lcs;
}

int main()
{
    vector<string> grades = {
        "ABCDBCBBBCABDDBCBCCCDDBBBCBBFFBCDDCDABABCDBBABABBCBBBBCDABBCCCBCABABABABBBBCDDBC",
        "BCCCABCCCCCCBCCCFFBCCCABABAABBCCABBCBCBCABBBBBAAABAAAAABDDABBCBCABBCCCBBBBABBBCD",
        "ABBBCDFFBCCCBBAABBABBCDDABAABCABCCABABBBBCBBBBCDABBBCCBBDDABABABBCBCFFABBCBCBCDD",
        "DDABCCCCBCBBBCBCABBCAAABCDBCBCBCBBABBCBCCCABABBBBBBBABBBABBBCDABBBBBBBBCCCABBCFF",
        "BBBCCDBCDDAABBCCABABBCAABBCDABBCABCCDDAAABBCCCABABABBCBBBCCDBCCCCDABBCBCBBCDCDBB",
        "BCABABCCDDDDBBCCCCBBCCBBCCBBBBCDBBBCABBBBBABCCBBABBBBCABDDABCCCCABAAAABCBCCCBBBC",
        "ABABBCCDBCBBCCBCBCABDDBCCCBCBBBBABABABBBBCABCCBBCDCCBCBBBBAABBABABBBCCDDCDBCBCCC",
        "CDCDCDBBCDBBAACDBCBCABBCABBCDDBCCDBBBCCDDDCDCCCCBCABCCCDBBBCDDCCBBAABCBBBCCDCDDD",
        "CCBBABBBCCABABABCDBBBBCDBBBCCDFFBCCCBBAABCBBABABBCABBBCCABDDABBBBBABBCBBBBBCBBBC",
        "ABCCDDBBBBCCCCBBCCBCBCBBCCBBCCCDBBBCABABBBBCBBABCDAABBABAABCCCBBABCCDDBBBBCCBCCD",
        "ABABCDABBCBBBCBCCCABBCDDBCABABBBABCCABCDABABABCDABBBCCCDBCDDCCABABCCBBBBABABBBBC",
        "BCABBBBCABBCCCCDDDBBBCBBCCBBBCBCBCABBBBCABBCCDCDBCBBABCCABDDBCBCBBCDBBABCCCDCCAB",
        "DDDDBBBBAABCBCBBBCBBBCBCCCFFABABBBCCABBCCCCCAADDBBBBCCCCCCCCABBCABBBCCDDABBBCDBC",
        "CDABBBBCDDBCCDCCBBBBCDABABCCBCBCAABBBCFFBCCDBCBCAABBCDBBFFBCBBBCABBBDDCCBBABCDCC",
        "BBABBBDDBCBBCCBCABBBABBBDDBBABBCBCBBCCABBBABCCBCCCABBCBCABCCBCBCBCAABBBBCDCDDDAB",
        "BCBCCDCCCDCDDDABBBBCBBCDCCBCABDDBBBCCCABCCCCBCBCABCCBCCCBBABBBBBBBCCAABBCCABBCBC",
        "ABBBBBBBBBDDBCBCBCCCBBCDCCBCCCBBCCBBBCBCBBBCCDAACDBCABCCCCAACDABBCCCABCCBBABBBCC",
        "BCDDABCDCCDDABABBCBBBCCDBBBBCCBCABABCCBBCCBCBCABBCCCBBBCAAAAABABBCBBBBCCCCDDBCAB",
        "ABBBABFFCDBBCDBCFFDDBCCCBBDDBCCCCDBBABABAACCDDBBBBCDBCABAADDABDDABCDCDBCABBCBCAB",
        "BCBBCDABABBCCDBCBBABBCBBBCABBBABCCBCABBCCCABBCCDBBBCABCDBBBBBCFFBBAAABBCBCBCABBC"};

    string result = longestCommonSubsequence(grades);
    cout << "Longest Common Subsequence among student's grades: " << result << endl;
    return 0;
}
